# Generated by Django 2.1.2 on 2018-10-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181030_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='age',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
